#!/usr/bin/env python3
from pathlib import Path

root = Path(__file__).resolve().parents[1]
required = [
    'Journey Operating Hub',
    'leaderForm',
    'taskForm',
    'driveSteps',
    'localStorage',
    'Journey V3 live',
    'Resource Library',
    'Event Readiness',
    'Website Access Review',
    'gateOpenCount',
    'gateRows',
    'Launch Gate Review',
    'accessRows',
    'accessPendingCount',
    'accessLevelFilter',
    'accessStatusFilter',
    'Do not copy Alpha assets',
    'START HERE Pathway',
    'Planning Control Board',
    'Template Bundles',
    'Review Packet Preview',
    'startPathRows',
    'planningRows',
    'templateRows',
    'handoffSummary',
    'prototypeVersion',
    'Website Content Approval',
    'Website Content Approval Templates',
    'contentRows',
    'contentPendingCount',
    'contentReviewFilter',
    'contentStatusFilter',
    'WCR-001',
    'Publication handoff',
    'Deployment preparation',
    'BLD-001',
    'buildApprovalFilter',
    'buildStatusFilter',
    'buildPendingCount',
    'buildRows',
    'Website Build Backlog',
    'Strategy Control Board',
    'strategyRows',
    'strategyDocCount',
    'strategyQualityCount',
    'Alpha-Inspired Hub Target State',
    'Google Drive Import Manifest',
    'Strategy Review Queue',
    'strategyQueueCount',
    'Reviewing authority',
    'SRQ-006',
    'Duplicate Resolution Queue',
    'duplicateRows',
    'duplicatePendingCount',
    'dashboardDuplicateCount',
    'DRQ-008',
    'Non-deletion boundary',
    'Template Improvement Queue',
    'templateImprovementRows',
    'templateImprovementPendingCount',
    'dashboardTemplateImprovementCount',
    'TIQ-012',
    'Template Acceptance Checklist',
    'templateAcceptanceRows',
    'templateAcceptancePendingCount',
    'dashboardTemplateAcceptanceCount',
    'TAC-012',
    'Organizational Implementation Board',
    'implementationRows',
    'implementationPendingCount',
    'dashboardImplementationCount',
    'OIB-006',
    'Non-automation boundary',
    'Implementation Session Pack',
    'sessionRows',
    'sessionPendingCount',
    'dashboardSessionCount',
    'ISP-010',
    'Session item',
]
for name in ('site/index.html', 'site/operating-hub-prototype.html'):
    html = root.joinpath(name).read_text(encoding='utf-8')
    missing = [item for item in required if item not in html]
    if missing:
        raise SystemExit(f'{name} missing prototype markers: {missing}')
    if 'http://' in html or 'https://' in html:
        raise SystemExit(f'{name} should not depend on external URLs')
print('site prototype tests passed')
